# -------------------------------
# Configuration for Whisper STT
# -------------------------------
whisper:
  model: "distil-small.en" # Name of the Whisper model to use for speech-to-text.
  sample_rate: 16000       # Audio sample rate (in Hz) for recording and transcription.

# -------------------------------
# Configuration for LM Studio (Chat & TTS)
# -------------------------------
lm:
  api_url: "http://127.0.0.1:1234/v1"  # Base URL for the LM Studio inference server.
  
  chat:
    endpoint: "/chat/completions"       # API endpoint for chat-based text generation.
    model: "gemma-3-12b-it"             # Model identifier for chat generation.
    system_prompt: "You are a helpful assistant."  # System prompt to set the context.
    max_tokens: 256                     # Increased for more coherent responses.
    temperature: 0.7                    # Sampling temperature; controls randomness.
    top_p: 0.9                          # Top-p (nucleus sampling) value.
    repetition_penalty: 1.1             # Penalty factor to reduce repetitive outputs.
    use_context: true                   # Ongoing conversation vs. one shot commands

  tts:
    endpoint: "/completions"            # API endpoint for text-to-speech synthesis.
    model: "orpheus-3b-0.1-ft"    # Model identifier for TTS synthesis.
    default_voice: "tara"               # Default voice for TTS output.
    max_tokens: 4096                    # Optimal for Orpheus.
    temperature: 0.6                    # Sampling temperature for TTS.
    top_p: 0.9                          # Top-p sampling value for TTS generation.
    repetition_penalty: 1.0             # Penalty to prevent repetitive TTS output.
    speed: 1.0                          # More natural speed.

# -------------------------------
# TTS Audio Output Configuration
# -------------------------------
tts:
  sample_rate: 24000          # Sample rate (in Hz) for the generated TTS audio.
  buffer_duration_ms: 1000     # Samples to collect before starting playback
  start_delay_ms: 500         # Delay after last generated sample before starting playback
  max_words: 80               # Maximum number of words per segment when splitting long TTS responses.

# -------------------------------
# Audio Device Configuration
# -------------------------------
audio:
  input_device: null          # Specify input device ID, or leave null to use the system default.
  output_device: null         # Specify output device ID, or leave null to use the system default.

# -------------------------------
# Voice Activity Detection (VAD) Configuration
# -------------------------------
vad:
  silence_threshold_ms: 1500  # Duration (in ms) of consecutive silence to stop recording.
  silence_threshold_wake_word_ms: 1000  # Duration (in ms) of consecutive silence to stop recording.
  voice_confidence_threshold: 0.7    # Minimum confidence for active speech.
  silence_confidence_threshold: 0.3    # Maximum confidence for silence.

# -------------------------------
# Wake Word Detection Configuration
# -------------------------------
wakeword:
  enabled: true               # Whether wake word detection is enabled.
  phrase: "Bitch"         # Wake word phrase (case insensitive).
